export const SIGN_UP_BEGIN = 'SIGN_UP_BEGIN';
export const SIGN_UP_FINISHED = 'SIGN_UP_FINISHED';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_IN_BEGIN = 'SIGN_IN_BEGIN';
export const SIGN_IN_FINISHED = 'SIGN_IN_FINISHED';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_BEGIN = 'SIGN_OUT_BEGIN';
export const SIGN_OUT_FINISHED = 'SIGN_OUT_FINISHED';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
export const RESET_SIGN_ERRORS = 'RESET_SIGN_ERRORS';
export const LOAD_LOCAL_SIGN_IN_INFO_BEGIN = 'LOAD_LOCAL_SIGN_IN_INFO_BEGIN';
export const LOAD_LOCAL_SIGN_IN_INFO_FINISHED =
  'LOAD_LOCAL_SIGN_IN_INFO_FINISHED';
export const LOAD_LOCAL_SIGN_IN_INFO_ERROR = 'LOAD_LOCAL_SIGN_IN_INFO_ERROR';
