export const ADD_COLLABORATOR = 'ADD_COLLABORATOR';
export const SET_COLLABORATOR_EXIST_STATUS = 'SET_COLLABORATOR_CHECK_STATUS';
export const LOAD_COLLABORATORS = 'LOAD_COLLABORATORS';
export const CLEAR_SELECTED_COLLABORATORS = 'CLEAR_SELECTED_COLLABORATORS';
export const SELECT_COLLABORATOR = 'SELECT_COLLABORATOR';
export const UNSELECT_COLLABORATOR = 'UNSELECT_COLLABORATOR';
export const SET_COLLABORATOR_PENDING = 'SET_COLLABORATOR_PENDING';
export const SET_COLLABORATOR_SELECTED = 'SET_COLLABORATOR_SELECTED';
export const SET_COLLABORATOR_UNSELECTED = 'SET_COLLABORATOR_UNSELECTED';
export const SET_COLLABORATOR_ERROR = 'SET_COLLABORATOR_ERROR';
export const SET_BUSY = 'SET_BUSY';
export const SUBSCRIBE_TO_CURRENT_SHOPPING_LIST_RECEIVERS =
  'SUBSCRIBE_TO_CURRENT_SHOPPING_LISTS_RECEIVERS';
export const UNSUBSCRIBE_FROM_CURRENT_SHOPPING_LIST_RECEIVERS =
  'UNSUBSCRIBE_FROM_CURRENT_SHOPPING_LIST_RECEIVERS';
export const UPDATE_RECEIVERS = 'UPDATE_RECEIVERS';
