export const CHECK_USER_EXISTENCE_BEGIN = 'CHECK_USER_EXISTENCE';
export const CHECK_USER_EXISTENCE_FINISH = 'CHECK_USER_EXISTENCE_FINISH';
export const CHECK_USER_EXISTENCE_ERROR = 'CHECK_USER_EXISTENCE_ERROR';
export const CLEAR_POTENTIAL_COLLABORATOR_DATA =
  'CLEAR_POTENTIAL_COLLABORATOR_DATA';
