// export const CHECK_USER_EXISTENCE_BEGIN = 'CHECK_USER_EXISTENCE';
// export const CHECK_USER_EXISTENCE_FINISH = 'CHECK_USER_EXISTENCE_FINISH';
// export const CHECK_USER_EXISTENCE_ERROR = 'CHECK_USER_EXISTENCE_ERROR';
// export const CLEAR_POTENTIAL_COLLABORATOR_DATA =
//   'CLEAR_POTENTIAL_COLLABORATOR_DATA';
// export const SEND_TEXT_MESSAGE_BEGIN = 'SEND_TEXT_MESSAGE_BEGIN';
// export const SEND_TEXT_MESSAGE_FINISH = 'SEND_TEXT_MESSAGE_FINISH';
// export const SEND_TEXT_MESSAGE_ERROR = 'SEND_TEXT_MESSAGE_ERROR';
