export const CSL_CREATE_SHOPPING_LIST = 'CSL_CREATE_SHOPPING_LIST';
export const CSL_ADD_PRODUCT = 'CSL_ADD_PRODUCT';
export const CSL_UPDATE_PRODUCT = 'CSL_UPDATE_PRODUCT';
export const CSL_SET_PRODUCT_STATUS_BEGIN = 'CSL_SET_PRODUCT_STATUS_BEGIN';
export const CSL_SET_PRODUCT_STATUS_FINISHED =
  'CSL_SET_PRODUCT_STATUS_FINISHED';
export const CSL_SET_PRODUCT_STATUS_ERROR = 'CSL_SET_PRODUCT_STATUS_ERROR';
export const CSL_REMOVE_PRODUCT_BEGIN = 'CSL_REMOVE_PRODUCT_BEGIN';
export const CSL_REMOVE_PRODUCT_FINISHED = 'CSL_REMOVE_PRODUCT_FINISHED';
export const CSL_REMOVE_PRODUCT_ERROR = 'CSL_REMOVE_PRODUCT_ERROR';
export const CSL_ADD_PRODUCTS = 'CSL_ADD_PRODUCTS';
export const CSL_UPDATE_PRODUCTS = 'CSL_UPDATE_PRODUCTS';
export const CSL_DELETE_PRODUCTS = 'CSL_DELETE_PRODUCTS';
export const CSL_SUBSCRIBE_TO_SHOPPING_LIST_BEGIN =
  'CSL_SUBSCRIBE_TO_SHOPPING_LIST_BEGIN';
export const CSL_SUBSCRIBE_TO_SHOPPING_LIST_FINISHED =
  'CSL_SUBSCRIBE_TO_SHOPPING_LIST_FINISHED';
export const CSL_SUBSCRIBE_TO_SHOPPING_LIST_ERROR =
  'CSL_SUBSCRIBE_TO_SHOPPING_LIST_ERROR';
export const CSL_UPDATE_SHOPPING_LIST = 'CSL_UPDATE_SHOPPING_LIST';
export const CSL_SUBSCRIBE_TO_SHARED_SHOPPING_LIST_LOADING_STATUS =
  'CSL_SUBSCRIBE_TO_SHARED_SHOPPING_LIST_LOADING_STATUS';
export const CSL_SET_SHARED_LIST_LOADING = 'CSL_SET_SHARED_LIST_LOADING';
export const CSL_LOAD_UNITS = 'CSL_LOAD_UNITS';
export const CSL_LOAD_CLASSES = 'CSL_LOAD_CLASSES';
// export const CSL_UPDATE_SHOPPING_LIST = 'CSL_UPDATE_SHOPPING_LIST';
