export const LOAD_ALL_SHOPPING_LISTS = 'LOAD_ALL_SHOPPING_LISTS';
export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST';
export const LOAD_UNITS = 'LOAD_UNITS';
export const LOAD_CLASSES = 'LOAD_CLASSES';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const LOAD_SHOPPING_LIST = 'LOAD_SHOPPING_LIST';
