export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST';
export const LOAD_UNITS = 'LOAD_UNITS';
export const LOAD_CLASSES = 'LOAD_CLASSES';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_SHOPPING_LIST_BEGIN = 'REMOVE_SHOPPING_LIST_BEGIN';
export const REMOVE_SHOPPING_LIST_FINISHED = 'REMOVE_SHOPPING_LIST_FINISHED';
export const REMOVE_SHOPPING_LIST_ERROR = 'REMOVE_SHOPPING_LIST_ERROR';
export const SET_PRODUCT_STATUS = 'SET_PRODUCT_STATUS';
export const SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_BEGIN =
  'SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_BEGIN';
export const SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_FINISHED =
  'SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_FINISHED';
export const SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_ERROR =
  'SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_ERROR';
export const UPDATE_LIST_OF_SHOPPING_LISTS = 'UPDATE_LIST_OF_SHOPPING_LISTS';
export const SUBSCRIBE_TO_SHOPPING_LIST_BEGIN =
  'SUBSCRIBE_TO_SHOPPING_LIST_BEGIN';
export const SUBSCRIBE_TO_SHOPPING_LIST_FINISHED =
  'SUBSCRIBE_TO_SHOPPING_LIST_FINISHED';
export const SUBSCRIBE_TO_SHOPPING_LIST_ERROR =
  'SUBSCRIBE_TO_SHOPPING_LIST_ERROR';
export const UPDATE_SHOPPING_LIST = 'UPDATE_SHOPPING_LIST';
export const REMOVE_PRODUCT_BEGIN = 'REMOVE_PRODUCT_BEGIN';
export const REMOVE_PRODUCT_FINISHED = 'REMOVE_PRODUCT_FINISHED';
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';
export const SET_SEND_LISTS_LOADING = 'SET_SEND_LISTS_LOADING';
export const SET_RECEIVED_LISTS_LOADING = 'SET_RECEIVED_LISTS_LOADING';
export const SUBSCRIBE_TO_SHARED_LISTS_OF_SHOPPING_LISTS_LOADING_STATUS =
  'SUBSCRIBE_TO_SHARED_LISTS_OF_SHOPPING_LISTS_LOADING_STATUS';
