export const SL_REMOVE_SHOPPING_LIST_BEGIN = 'SL_REMOVE_SHOPPING_LIST_BEGIN';
export const SL_REMOVE_SHOPPING_LIST_FINISHED =
  'SL_REMOVE_SHOPPING_LIST_FINISHED';
export const SL_REMOVE_SHOPPING_LIST_ERROR = 'SL_REMOVE_SHOPPING_LIST_ERROR';
export const SL_SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_BEGIN =
  'SL_SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_BEGIN';
export const SL_SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_FINISHED =
  'SL_SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_FINISHED';
export const SL_SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_ERROR =
  'SL_SUBSCRIBE_TO_LIST_OF_SHOPPING_LISTS_ERROR';
export const SL_UPDATE_LIST_OF_SHOPPING_LISTS =
  'SL_UPDATE_LIST_OF_SHOPPING_LISTS';
export const SL_UNSUBSCRIBE_FROM_LIST_OF_SHOPPING_LISTS =
  'SL_UNSUBSCRIBE_FROM_LIST_OF_SHOPPING_LISTS';
export const SL_SUBSCRIBE_TO_SHARED_LISTS_OF_SHOPPING_LISTS_LOADING_STATUS =
  'SL_SUBSCRIBE_TO_SHARED_LISTS_OF_SHOPPING_LISTS_LOADING_STATUS';
export const SL_SET_SEND_LISTS_LOADING = 'SL_SET_SEND_LISTS_LOADING';
export const SL_SET_RECEIVED_LISTS_LOADING = 'SL_SET_RECEIVED_LISTS_LOADING';
export const SL_UNSUBSCRIBE_FROM_SHARED_LISTS_OF_SHOPPING_LISTS_LOADING_STATUS =
  'SL_UNSUBSCRIBE_FROM_SHARED_LISTS_OF_SHOPPING_LISTS_LOADING_STATUS';
