export const USERS_ROOT = 'USERS_ROOT';
export const USER_SEND = 'USER_SEND';
export const USER_SEND_DELIM = 'USER_SEND_DELIM';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_RECEIVED_DELIM = 'USER_RECEIVED_DELIM';
export const SHARED_SHOPPING_LISTS_ROOT = 'SHARED_SHOPPING_LISTS_ROOT';
export const SHARED_SHOPPING_LISTS_ROOT_DELIM =
  'SHARED_SHOPPING_LISTS_ROOT_DELIM';
export const SHARED_SHOPPING_LIST = 'SHARED_SHOPPING_LIST';
export const SHARED_SHOPPING_LIST_DELIM = 'SHARED_SHOPPING_LIST_DELIM';
