export const LIST_OF_SHOPPING_LISTS_CHANGED = 'LIST_OF_SHOPPING_LISTS_CHANGED';
export const SHOPPING_LIST_CHANGED = 'SHOPPING_LIST_CHANGED';
export const UNITS_CHANGED = 'UNITS_CHANGED';
export const CLASSES_CHANGED = 'CLASSES_CHANGED';
export const SIGN_IN_INFO_CHANGED = 'SIGN_IN_INFO_CHANGED';
